@extends('layout.main-layout')
@section('content')
<h1>test</h1>
@push("addon-script")
    <script>
         var fakultas = [
            { value: 'Fakultas Pertanian (FAPERTA)', data: 'Fakultas Pertanian (FAPERTA)' },
            { value: 'Fakultas Ekonomi dan Bisnis (FEB)', data: 'Fakultas Ekonomi dan Bisnis (FEB)' },
            { value: 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP)', data: 'Fakultas Keguruan dan Ilmu Pendidikan (FKIP)' },
            { value: 'Fakultas Hukum (FH)', data: 'Fakultas Hukum (FH)' },
            { value: 'Fakultas Ilmu Sosial dan Ilmu Politik (FISIP)', data: 'Fakultas Ilmu Sosial dan Ilmu Politik (FISIP)' },
            { value: 'Fakultas Teknik (FT)', data: 'Fakultas Teknik (FT)' },
            { value: 'Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA)', data: 'Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA)' },
            { value: 'Fakultas Kedokteran dan Ilmu Kesehatan (FKIK)', data: 'Fakultas Kedokteran dan Ilmu Kesehatan (FKIK)' },
            { value: 'Fakultas Sastra/Ilmu Budaya', data: 'Fakultas Sastra/Ilmu Budaya' },
            { value: 'Fakultas Seni Rupa dan Desain', data: 'Fakultas Seni Rupa dan Desain' },
            { value: 'Fakultas Ilmu Keperawatan', data: 'Fakultas Ilmu Keperawatan' },
            { value: 'Fakultas Ushuluddin', data: 'Fakultas Ushuluddin' },
            { value: 'Fakultas Dirasat Islamiyah', data: 'Fakultas Dirasat Islamiyah' },
            { value: 'Fakultas Pariwisata dan Perhotelan', data: 'Fakultas Pariwisata dan Perhotelan' },
            { value: 'Fakultas Kedokteran Gigi: Pendidikan Dokter Gigi', data: 'Fakultas Kedokteran Gigi: Pendidikan Dokter Gigi' },
            { value: 'Fakultas Farmasi: Farmasi', data: 'Fakultas Farmasi: Farmasi' },
            { value: 'Fakultas Kesehatan Masyarakat', data: 'Fakultas Kesehatan Masyarakat' },
            { value: 'Fakultas Ilmu Komputer', data: 'Fakultas Ilmu Komputer' },
            { value: 'Fakultas Ilmu Pengetahuan Budaya', data: 'Fakultas Ilmu Pengetahuan Budaya' },
            { value: 'Fakultas Psikologi', data: 'Fakultas Psikologi' },
            { value: 'Fakultas Ilmu Administrasi', data: 'Fakultas Ilmu Administrasi' },
            { value: 'Fakultas Filsafat', data: 'Fakultas Filsafat' },
            { value: 'Fakultas Kedokteran Hewan', data: 'Fakultas Kedokteran Hewan' },
            { value: 'Fakultas Kehutanan', data: 'Fakultas Kehutanan' },
            { value: 'Fakultas Teknik Pertambangan dan Perminyakan', data: 'Fakultas Teknik Pertambangan dan Perminyakan' },
            { value: 'Fakultas Ilmu dan Teknologi Kebumian', data: 'Fakultas Ilmu dan Teknologi Kebumian' },
            { value: 'Fakultas Teknologi Industri', data: 'Fakultas Teknologi Industri' },
            { value: 'Fakultas Teknik Mesin dan Dirgantara', data: 'Fakultas Teknik Mesin dan Dirgantara' },
            { value: 'Fakultas Teknik Sipil dan Lingkungan', data: 'Fakultas Teknik Sipil dan Lingkungan' },
            { value: 'Fakultas Seni Rupa dan Desain', data: 'Fakultas Seni Rupa dan Desain' },
            { value: 'Fakultas Perikanan dan Ilmu Kelautan', data: 'Fakultas Perikanan dan Ilmu Kelautan' },
            { value: 'Fakultas Peternakan', data: 'Fakultas Peternakan' },
            { value: 'Pendidikan Bidan', data: 'Pendidikan Bidan' },
            { value: 'Program Vokasi', data: 'Program Vokasi' },
            { value: 'POLRI', data: 'POLRI' },
            { value: 'TNI', data: 'TNI' },
            { value: 'Politeknik Keuangan Negara STAN (PKN STAN)', data: 'Politeknik Keuangan Negara STAN (PKN STAN)' },
            { value: 'Institut Pemerintahan Dalam Negeri (IPDN)', data: 'Institut Pemerintahan Dalam Negeri (IPDN)' },
            { value: 'Politeknik Ilmu Pemasyarakatan (Poltekip)', data: 'Politeknik Ilmu Pemasyarakatan (Poltekip)' },
            { value: 'Politeknik Imigrasi (Poltekim)', data: 'Politeknik Imigrasi (Poltekim)' },
            { value: 'Politeknik Transportasi Darat Indonesia (PTDI)', data: 'Politeknik Transportasi Darat Indonesia (PTDI)' },
            { value: 'Politeknik Perkeretaapian Indonesia (PPI)', data: 'Politeknik Perkeretaapian Indonesia (PPI)' },
            { value: 'Sekolah Tinggi Ilmu Pelayaran (STIP)', data: 'Sekolah Tinggi Ilmu Pelayaran (STIP)' },
            { value: 'Politeknik Penerbangan Indonesia (PPI)', data: 'Politeknik Penerbangan Indonesia (PPI)' },
            { value: 'Politeknik Statistika STIS (Polstat STIS)', data: 'Politeknik Statistika STIS (Polstat STIS)' },
            { value: 'Sekolah Tinggi Meteorologi, Klimatologi, dan Geofisika (STMKG)', data: 'Sekolah Tinggi Meteorologi, Klimatologi, dan Geofisika (STMKG)' },
            { value: 'Sekolah Tinggi Intelijen Negara (STIN)', data: 'Sekolah Tinggi Intelijen Negara (STIN)' },
            { value: 'Politeknik Siber dan Sandi Negara (Poltek SSN)', data: 'Politeknik Siber dan Sandi Negara (Poltek SSN)' },
            { value: 'Politeknik Keuangan Negara STAN', data: 'Politeknik Keuangan Negara STAN' },
            { value: 'Politeknik Rekayasa', data: 'Politeknik Rekayasa' },
            { value: 'Fakultas Sains dan Teknologi', data: 'Fakultas Sains dan Teknologi' },
            { value: 'Fakultas Teknik Sipil', data: 'Fakultas Teknik Sipil' },
            { value: 'Fakultas Teknis Mesin', data: 'Fakultas Teknis Mesin' },
            { value: 'Politeknik Statistika STIS', data: 'Politeknik Statistika STIS' },
            { value: 'Program Studi Desain Komunikasi Visual', data: 'Program Studi Desain Komunikasi Visual' },
            { value: 'Program Studi Seni Kriya', data: 'Program Studi Seni Kriya' },
            { value: 'Fakultas Seni Rupa dan Desain (FSRD)', data: 'Fakultas Seni Rupa dan Desain (FSRD)'  },
            { value: 'Pendidikan Matematika', data: 'Pendidikan Matematika' },
            { value: 'Pendidikan Fisika', data: 'Pendidikan Fisika' },
            { value: 'Pendidikan Biologi', data: 'Pendidikan Biologi' },
            { value: 'Pendidikan Kimia', data: 'Pendidikan Kimia' },
            { value: 'Pendidikan Agama Islam', data: 'Pendidikan Agama Islam' },
            { value: 'Pendidikan Bahasa Arab', data: 'Pendidikan Bahasa Arab' },
            { value: 'Pendidikan Guru Madrasah Ibtidaiyah', data: 'Pendidikan Guru Madrasah Ibtidaiyah' },
            { value: 'Pendidikan Bahasa Inggris', data: 'Pendidikan Bahasa Inggris' },
            { value: 'Hukum Keluarga', data: 'Hukum Keluarga' },
            { value: 'Hukum Ekonomi Syariah', data: 'Hukum Ekonomi Syariah' },
            { value: 'Perbandingan Mazhab', data: 'Perbandingan Mazhab' },
            { value: 'Hukum Pidana Islam', data: 'Hukum Pidana Islam' },
            { value: 'Aqidah dan Filsafat islam', data: 'Aqidah dan Filsafat islam' },
            { value: 'Sosiologi Agama', data: 'Sosiologi Agama' },
            { value: 'Studi Agama Agama', data: 'Studi Agama Agama' },
            { value: 'Ilmu Al-Quran dan Tafsir', data: 'Ilmu Al-Quran dan Tafsir' },
            { value: 'Komunikasi dan Penyiaran Islam', data: 'Komunikasi dan Penyiaran Islam' },
            { value: 'Bimbingan dan Konseling Islam', data: 'Bimbingan dan Konseling Islam' },
            { value: 'Manajemen Dakwah', data: 'Manajemen Dakwah' },
            { value: 'Pengembangan Masyarakat Islam', data: 'Pengembangan Masyarakat Islam' },
            { value: 'Bahasa dan Sastra Arab', data: 'Bahasa dan Sastra Arab' },
            { value: 'Sejarah dan Kebudayaan Islam', data: 'Sejarah dan Kebudayaan Islam' },
            { value: 'Manajemen Pendidikan Islam', data: 'Manajemen Pendidikan Islam' },
            { value: 'Hukum Tata Negara', data: 'Hukum Tata Negara' },
            { value: 'Pendidikan Islam Anak Usia Dini', data: 'Pendidikan Islam Anak Usia Dini' },
            { value: 'Ekonomi Syariah', data: 'Ekonomi Syariah' },
            { value: 'Perbankan Syariah', data: 'Perbankan Syariah' },
            { value: 'Ilmu Hadis', data: 'Ilmu Hadis' },
            { value: 'Fakultas Syariah dan Hukum', data: 'Fakultas Syariah dan Hukum' },
            { value: 'Tarbiyah dan Keguruan', data: 'Tarbiyah dan Keguruan' },
            { value: 'Fakultas Ushuluddin dan Filsafat', data: 'Fakultas Ushuluddin dan Filsafat' },
            { value: 'Dakwah dan Komunikasi', data: 'Dakwah dan Komunikasi' },
            { value: 'Fakultas Ekonomi dan Bisnis', data: 'Fakultas Ekonomi dan Bisnis' },
            { value: 'Fakultas Ilmu Sosial dan Pemerintahan', data: 'Fakultas Ilmu Sosial dan Pemerintahan' },
            { value: 'Fakultas Psikologi', data: 'Fakultas Psikologi' },
            { value: 'Fakultas Adab dan Humaniora', data: 'Fakultas Adab dan Humaniora' },
            { value: 'Fakultas Ekonomi dan Bisnis', data: 'Fakultas Ekonomi dan Bisnis' },
            { value: 'Fakultas Sains dan Teknologi', data: 'Fakultas Sains dan Teknologi' },
            { value: 'Fakultas Adab dan Humaniora', data: 'Fakultas Adab dan Humaniora' },
            { value: 'Jurusan Keperawatan Banda Aceh', data: 'Jurusan Keperawatan Banda Aceh' },
            { value: 'Jurusan Kebidanan', data: 'Jurusan Kebidanan' },
            { value: 'Jurusan Gizi', data: 'Jurusan Gizi' },
            { value: 'Jurusan Kesehatan Gigi', data: 'Jurusan Kesehatan Gigi' },
            { value: 'Jurusan Kesehatan Lingkungan', data: 'Jurusan Kesehatan Lingkungan' },
            { value: 'Jurusan Lingkungan Mandiri', data: 'Jurusan Lingkungan Mandiri' },
            { value: 'SDM Persawitan', data: 'SDM Persawitan' },
            { value: 'Teknik Arsitektur', data: 'Teknik Arsitektur' },
            { value: 'LP3I - Ekonomi', data: 'LP3I - Ekonomi' },
            { value: 'LP3I - Sekretaris', data: 'LP3I - Sekretaris' }];
                            
        function sendDataToServer(data) {
            $.ajax({
                url: '{{route('fakultas-save')}}',
                method: 'POST',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                contentType: 'application/json',
                data: JSON.stringify({ fakultas: data }),
                success: function(response) {
                    console.log('Success:', response);
                },
                error: function(xhr) {
                    console.error('xhr:', xhr);
                }
            });
        }
        console.log({fakultas})
        sendDataToServer(fakultas);
    </script>
@endpush

@endsection